Prevent muted people from voting.
DMOJ/online-judge pull request #1563
Opened 2020-10-04 23:01 UTC by ehhthing

2020-10-04 23:05 UTC, kiritofeng approved these changes
LGTM

2020-10-04 23:05 UTC, quantum5 requested changes

2020-10-04 23:05 UTC, quantum5 commented on judge/views/comment.py
> +    if request.profile.mute:
I find your lack of whitespace before this line disturbing.

2020-10-04 23:11 UTC, quantum5 approved these changes

2020-10-17 02:22 UTC, Xyene approved these changes

2020-10-17 02:23 UTC, merged