Updated activation_email.html to solve Issue #560
DMOJ/online-judge pull request #1916
Opened 2022-04-12 21:02 UTC by stefanZorcic

2022-04-12 21:07 UTC, stefanZorcic commented
Images of new email design, disregard clutter from {} elements
<img width="547" alt="Screen Shot 2022-04-12 at 4 53 51 PM" src="https://user-images.githubusercontent.com/70064280/163054769-520aa385-8079-4ef9-bfe3-f2c69b97aa1d.png">
<img width="549" alt="Screen Shot 2022-04-12 at 4 53 56 PM" src="https://user-images.githubusercontent.com/70064280/163054784-71fe49c8-a5aa-43a0-b0b3-6e65ffc97283.png">

2022-04-12 21:12 UTC, stefanZorcic commented
Updated image
<img width="539" alt="Screen Shot 2022-04-12 at 5 12 31 PM" src="https://user-images.githubusercontent.com/70064280/163055495-5a3a5311-5463-4c80-9f51-a561bc6190a5.png">
<img width="544" alt="Screen Shot 2022-04-12 at 5 12 36 PM" src="https://user-images.githubusercontent.com/70064280/163055505-39468457-dcd4-4743-b9fb-efedf4868d7e.png">
s

2022-04-12 21:13 UTC, stefanZorcic commented
Updated image
<img width="534" alt="Screen Shot 2022-04-12 at 5 13 26 PM" src="https://user-images.githubusercontent.com/70064280/163055630-43375117-8d1d-4451-beeb-5630ad0f0487.png">
<img width="523" alt="Screen Shot 2022-04-12 at 5 13 31 PM" src="https://user-images.githubusercontent.com/70064280/163055639-7f3bb7ed-f5f4-4fab-a921-920f90ee3056.png">
s

2022-04-15 05:20 UTC, int-y1 requested changes

2022-04-15 05:20 UTC, int-y1 commented on templates/registration/activation_email.html
> +        <p style="color: white">See you soon!</p>
I don't see a reason to have `See you soon!` in both the `if` and `else` branches. Just put it before the if-statement.

Also, this white text doesn't work.
![Capture](https://user-images.githubusercontent.com/14223529/163523663-d08cd0fc-6936-451e-b8a9-b264efc45a2c.PNG)

2022-04-15 05:20 UTC, int-y1 commented on templates/registration/activation_email.html
Remove this empty line.

2022-04-15 05:20 UTC, int-y1 commented on templates/registration/activation_email.html
> +            <img style="display:table;margin-left: auto;margin-right: auto;"src="https://avatars1.githubusercontent.com/u/6934864?v=3&s=101" width="35%" height="30%">
`width="35%" height="30%"` creates a bad aspect ratio.

2022-04-15 05:20 UTC, int-y1 commented on templates/registration/activation_email.html
> +            <a href="http://{{ site.domain }}/accounts/activate/{{ activation_key }}/">http://{{ site.domain }}/accounts/activate/{{ activation_key }}</a>
`https` is more common nowadays.

2022-04-15 05:20 UTC, int-y1 commented on templates/registration/activation_email.html
> +        <i>Alternatively, you can reply to this message to activate your account</i>
missing period

2022-04-15 05:23 UTC, int-y1 commented on templates/registration/activation_email.html
> +            <img style="display:table;margin-left: auto;margin-right: auto;"src="https://avatars1.githubusercontent.com/u/6934864?v=3&s=101" width="35%" height="30%">
Try using `max-width` and `max-height` in the `style`.

2022-04-15 06:25 UTC, int-y1 commented on templates/registration/activation_email.html
> +        <h1 style="font-size:30px;display:inline;vertical-align: middle">Welcome to DMOJ!</h1>
Use `{{ SITE_NAME }}`, not `DMOJ`

2022-11-01 03:59 UTC, Xyene commented
Superseded by https://github.com/DMOJ/online-judge/pull/2028.

2022-11-01 03:59 UTC, closed without merging