sorted organizations by name
DMOJ/online-judge pull request #2262
Opened 2023-06-21 03:09 UTC by jazyz

2023-06-21 05:33 UTC, quantum5 requested changes
Why are you sorting in Python? This is obviously a database level operation. Imagine what happens when we are forced to paginate the organization page.

2023-06-21 05:39 UTC, kiritofeng commented on judge/views/organization.py
> +    def get_context_data(self, **kwargs):
Please fix your code style to be consistent with the rest of our codebase. You can check this locally (without having to wait for us to approve the linter run) by running `flake8` yourself.

2023-06-21 23:53 UTC, jazyz commented
Now sorted in database level

2023-06-22 00:01 UTC, Riolku approved these changes
LGTM assuming CI passes

2023-06-22 00:04 UTC, Ninjaclasher approved these changes
LGTM

2023-06-22 00:09 UTC, quantum5 approved these changes

2023-07-12 01:12 UTC, merged